#!/usr/bin/env bash
# Write a script to install and configure HAProxy on lb-01 server
# Setup HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm program
# Check that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

# edit config file
server_config=\
"
frontend barackhalogen-frontend
        bind *:80
        mode http
        default_backend barackhalogen-backend
backend barackhalogen-backend
        balance roundrobin
        server 71109-web-01 52.23.245.180:80 check
        server 71109-web-02 54.175.246.134:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# this next line will enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
